[alembic]
script_location = alembic
prepend_sys_path = .
sqlalchemy.url = postgresql+psycopg://mailmind:mailmind@postgres:5432/mailmind

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

# handlers, formatters, and logger configurations
[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

# Logger for SQLAlchemy engine
[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

# Logger for Alembic
[logger_alembic]
level = INFO
handlers =
qualname = alembic

# Handler for console output
[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

# Formatter for log messages
[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
